<x-dashboard.card 
    :implemented="$implemented" 
    :metodologi="$metodologi"
    :total-innovators="$totalInnovators" 
    :total-innovators-male="$totalInnovatorsMale"
    :total-innovators-female="$totalInnovatorsFemale" 
    :total-innovatores-outsource="$totalInnovatoresOutsource" 
    :total-active-events="$totalActiveEvents" 
    :idea-box="$ideaBox" 
    :total-implemented-innovations="$totalImplementedInnovations" 
    :total-idea-box-innovations="$totalIdeaBoxInnovations"

    :years="$years"
    :age-groups="$ageGroups"
    :age-data="$ageData"
    :age-labels="$ageLabels"
    :age-counts="$ageCounts"
    :age-total="$ageTotal"
/>